kind: swe
task_names:
- django__django-10973
- django__django-11087
- django__django-11490
- django__django-14017
- django__django-14034
- django__django-14155
- django__django-14170
- django__django-14315
- django__django-14376
- django__django-14534
- django__django-14792
- pylint-dev__pylint-4970
- pylint-dev__pylint-6386
- pylint-dev__pylint-7080
- pytest-dev__pytest-10051
- pytest-dev__pytest-10081
- pytest-dev__pytest-5840
- pytest-dev__pytest-7205
- sphinx-doc__sphinx-10323
- sphinx-doc__sphinx-10435
- sphinx-doc__sphinx-10673
- sphinx-doc__sphinx-7748
- sphinx-doc__sphinx-8056
- sphinx-doc__sphinx-9673
- sympy__sympy-12419
- sympy__sympy-13091
- sympy__sympy-13798
- sympy__sympy-13974
- sympy__sympy-23950
- sympy__sympy-24443
- django__django-10999
- django__django-11477
- django__django-11728
- pylint-dev__pylint-6528
- pytest-dev__pytest-7490
- sphinx-doc__sphinx-7462
- sphinx-doc__sphinx-9281
- sympy__sympy-17318
- sympy__sympy-18763
