kind: terminal_bench
task_names:
- adaptive-rejection-sampler
- circuit-fibsqrt
- write-compressor
- chess-best-move
- polyglot-c-py
- llm-inference-batching-scheduler
- sqlite-db-truncate
- make-mips-interpreter
- torch-tensor-parallelism
- custom-memory-heap-crash
- bn-fit-modify
- cobol-modernization
- sam-cell-seg
- extract-elf
- sparql-university
- path-tracing-reverse
- constraints-scheduling
- overfull-hbox
- distribution-search
- build-cython-ext
- prove-plus-comm
- code-from-image
- hf-model-inference
- large-scale-text-editing
- regex-log
- nginx-request-logging
- sqlite-with-gcov
- count-dataset-tokens
- pytorch-model-recovery
- pypi-server
- modernize-scientific-stack
- portfolio-optimization
- cancel-async-tasks
- build-pmars
- kv-store-grpc
- multi-source-data-merger
- fix-git
- log-summary-date-ranges
- build-pov-ray
- caffe-cifar-10
- compile-compcert
- configure-git-webserver
- dna-assembly
- dna-insert
- extract-moves-from-video
- financial-document-processor
- fix-ocaml-gc
- gcode-to-text
- git-multibranch
- gpt2-codegolf
- headless-terminal
- install-windows-3.11
- largest-eigenval
- mailman
- make-doom-for-mips
- mcmc-sampling-stan
- merge-diff-arc-agi-task
- mteb-leaderboard
- mteb-retrieve
- path-tracing
- polyglot-rust-c
- protein-assembly
- pytorch-model-cli
- qemu-alpine-ssh
- qemu-startup
- query-optimize
- raman-fitting
- regex-chess
- reshard-c4-data
- rstan-to-pystan
- schemelike-metacircular-eval
- torch-pipeline-parallelism
- train-fasttext
- tune-mjcf
- video-processing
- winning-avg-corewars
