kind: terminal_bench
task_names:
- circuit-fibsqrt
- write-compressor
- chess-best-move
- polyglot-c-py
- llm-inference-batching-scheduler
- sqlite-db-truncate
- custom-memory-heap-crash
- bn-fit-modify
- cobol-modernization
- sam-cell-seg
- extract-elf
- path-tracing-reverse
- constraints-scheduling
- overfull-hbox
- distribution-search
- build-cython-ext
- prove-plus-comm
- code-from-image
- large-scale-text-editing
- regex-log
- sqlite-with-gcov
- count-dataset-tokens
- modernize-scientific-stack
- cancel-async-tasks
- build-pmars
- kv-store-grpc
- multi-source-data-merger
- fix-git
- log-summary-date-ranges
- configure-git-webserver
- make-doom-for-mips
- merge-diff-arc-agi-task
- mteb-retrieve
- polyglot-rust-c
- schemelike-metacircular-eval
- sparql-university
